---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphdb-dynatrace-testing-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kwami-sossoe/nosql-services-infra-apps.git
    targetRevision: HEAD
    path: projects/projects-base-apps/graphdb/features/dynatrace-testing/graphdb-statefulset-monitoring
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
