apiVersion: v1
kind: Service
metadata:
  name: graphdb
  labels:
    app: graphdb
    app.kubernetes.io/name: graphdb
    app.kubernetes.io/component: backend
spec:
  ports:
  - port: 7200
    targertport: 7200
    name: dbworkbench
  selector:
    app: graphdb
    app.kubernetes.io/name: graphdb
    app.kubernetes.io/component: backend
  