---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphdb-platform-argocd-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: graphdb-platform
  sources:
  - repoURL: 'http://maven.ontotext.com/repository/helm-public/'
    chart: graphdb  
    targetRevision: 10.6.1
    helm:
      valueFiles:
      - $values/root/graphdb/values-dev-tec.yaml
  - repoURL: 'https://github.com/kwami-sossoe/nosql-services-infra-apps.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true