---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphdb-platform-new
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: graphdb-platform-new
  source:
    repoURL: 'http://maven.ontotext.com/repository/helm-public/'
    targetRevision: 10.5.1
    chart: graphdb
    helm:
      values: |
        global:
          storageClass: "local-path"
        images:
          graphdb:
            registry: docker.io
            repository: ontotext/graphdb
            tag: "10.6.1"
        deployment:
          host: localhost
          protocol: https
          ingress:
            enabled: false
        graphdb:
          clusterConfig:
            nodesCount: 3
            clusterCreationTimeout: 1200
          node:
            license: graphdb-license
            securityContext:
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL
            initContainerSecurityContext:
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL
            startupProbe:
              httpGet:
                path: /protocol
                port: graphdb
              failureThreshold: 600
              initialDelaySeconds: 300
              timeoutSeconds: 5
              periodSeconds: 30
            livenessProbe:
              httpGet:
                path: /protocol
                port: graphdb
              initialDelaySeconds: 300
              timeoutSeconds: 5
              periodSeconds: 30
            podSpec:
              podAntiAffinity: false
          clusterProxy:
            securityContext:
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL
            serviceType: ClusterIP
            startupProbe:
              httpGet:
                path: /proxy/ready
                port: gdb-proxy-port
              failureThreshold: 600
              initialDelaySeconds: 300
              timeoutSeconds: 5
              periodSeconds: 30
            readinessProbe:
              httpGet:
                path: /proxy/ready
                port: gdb-proxy-port
              initialDelaySeconds: 300
              timeoutSeconds: 5
              periodSeconds: 30
            livenessProbe:
              httpGet:
                path: /proxy/health
                port: gdb-proxy-port
              initialDelaySeconds: 300
              timeoutSeconds: 5
              periodSeconds: 30
            podSpec:
              podAntiAffinity: false
            jobSecurityContext:
              runAsNonRoot: false
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              seccompProfile:
                type: RuntimeDefault
              capabilities:
                drop:
                  - ALL
          jobSecurityContext:
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
        createGraphdbCluster:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: "RuntimeDefault" 
            capabilities:
              drop:
              - ALL
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true