---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphdb-platform-argocd-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: graphdb-platform2
  source:
    repoURL: 'http://maven.ontotext.com/repository/helm-public/'
    targetRevision: 10.6.1
    chart: graphdb
    helm:
      parameters:
        - name: my.helm.key
          value: some-val
      valueFiles:
        - $values/root-projects/graphdb/root/values-dev-tec.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
