---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphdb-platform-argocd-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: graphdb-platform
  source:
    repoURL: 'http://maven.ontotext.com/repository/helm-public/'
    targetRevision: 10.5.1
    chart: graphdb
    helm:
      valueFiles:
        - $values/root-projects/graphdb/root/values-dev-tec.yaml
    # repoURL: 'https://github.com/kwami-sossoe/nosql-services-infra-apps.git'
    # targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true