---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphdb-platform-argocd-app2
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: graphdb-platform2
  sources:
  - repoURL: 'http://maven.ontotext.com/repository/helm-public/'
    chart: graphdb  
    targetRevision: 10.5.1
    helm:
      version: v3
      releaseName: graphdb-platform-helm-app2
      passCredentials: false
      valueFiles:
      - $values/projects/projects-base-apps/graphdb/selfservice/dev-tec/values-dev-tec.yaml
  - repoURL: 'https://github.com/kwami-sossoe/nosql-services-infra-apps.git'
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true