{{- if .Values.apps.argocd.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-by-argocd
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: ""
    kind: Namespace
  - group: apiregistration.k8s.io
    kind: APIService
  - group: policy
    kind: PodSecurityPolicy
  description: ArgoCD Project to manage Argocd by Argocd
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://artifactory.dt.renault.com/artifactory/cloud-transformation
  - europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
{{- end }}
