{{- if .Values.apps.externalSecretsOperator.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: external-secrets
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  description: External-secrets deployments
  destinations:
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: external-secrets-operator
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
{{- end }}
