{{- if .Values.apps.gatekeeper.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gatekeeper
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: constraints.gatekeeper.sh
    kind: "*"
  - group: templates.gatekeeper.sh
    kind: ConstraintTemplate
  - group: config.gatekeeper.sh
    kind: Config
  - group: status.gatekeeper.sh
    kind: ConstraintPodStatus
  - group: status.gatekeeper.sh
    kind: ConstraintTemplatePodStatus
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: apiregistration.k8s.io
    kind: APIService
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  - group: policy
    kind: PodSecurityPolicy
  description: Gatekeeper Project
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - https://gitlabee.dt.renault.com/cloud-migration/common/argocd-apps.git
  - https://gitlabee.dt.renault.com/digital-cloud-platform/infra/gcp-zone-primary/infra-argocd/gatekeeper-library.git
  - https://gitlabee.dt.renault.com/digital-cloud-platform/infra/argocd-apps.git
  - europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
{{- end }}
