{{- if .Values.apps.goldilocks.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: goldilocks
  namespace: argocd
spec:
  description: Goldilocks VPA Recommander
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  destinations:
  - namespace: goldilocks
    server: https://kubernetes.default.svc
  sourceRepos:
  - europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
{{- end }}
