{{- if .Values.extraApps.infraSecrets.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-secrets
  namespace: argocd
spec:
  description: Infra Secrets Project to manage platform secrets
  destinations:
  - namespace: infra-secrets
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
{{- end }}
