{{- if .Values.apps.mirrorregistry.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mirror-registry
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
  description: mirror-registry deployments
  destinations:
  - namespace: mirror-registry-system
    server: https://kubernetes.default.svc
  - namespace: monitoring
    server: https://kubernetes.default.svc
  - namespace: argocd
    server: https://kubernetes.default.svc
  - namespace: project-irn-70740-workspace-irn-70740
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - europe-docker.pkg.dev/irn-71889-adm-dev-ope-68/helm-gke-irn70740
{{- end }}