---
global:
  image:
    tag: "v2.9.7"

server:
  extraArgs:
    - --insecure

# helm install argocd -n argocd --create-namespace argo/argo-cd --version 5.53.0 -f argocd.yaml

# k3d cluster create dev --servers 3 --agents 5 -p "80:80@loadbalancer" -p "443:443@loadbalancer"
