apiVersion: v2
appVersion: "0.1.0"
description: |-
  Helm chart to deploy NoSQL services infrastructure.
name: nosql-services-infra-apps
version: 0.1.0
maintainers:
  - name: Kwami Seyram SOSSOE
    email: kwami-seyram-externe.sossoe@edf.fr
  - name: Anis BEN ----
    email: anis---@edf.fr