---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graphdb-monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kwami-sossoe/nosql-services-infra-apps.git
    targetRevision: HEAD
    path: root-projects/graphdb/features/graphdb-monitoring/graphdb-app
  destination:
    server: https://kubernetes.default.svc
    namespace: graphdb-monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true