{{- if .Values.apps.blackboxExporter.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: {{ include "blackboxExporter.appproject" . }}
  source:
    repoURL: {{ .Values.cluster.ociRepoUrl | quote }}
    targetRevision: {{ .Values.apps.blackboxExporter.targetRevision | quote }}
    chart: prometheus-blackbox-exporter
    helm:
      values: |
        blackbox-exporter:
          extraEnv:
            HTTP_PROXY: "{{ .Values.cluster.httpProxy }}"
            HTTPS_PROXY: "{{ .Values.cluster.httpProxy }}"
            NO_PROXY: "{{ .Values.cluster.noProxy }}, *.cluster.local"
          image:
            repository: {{ .Values.apps.blackboxExporter.blackboxExporterImageRepo }}
            tag: {{ .Values.apps.blackboxExporter.blackboxExporterImageTag }}
            {{-  if .Values.cluster.imagePullSecrets }}
            pullSecrets:
              - {{ toYaml (index .Values.cluster.imagePullSecrets 0).name }}
            {{- end }}
          resources:
            {{- .Values.apps.blackboxExporter.resources | toYaml | nindent 12 }}
          serviceMonitor:
              enabled: {{ .Values.apps.prometheus.enabled }}
              defaults:
                labels:
                  prometheus: {{ include "prometheus.label" . | quote }}
              targets:
              {{- .Values.apps.blackboxExporter.targets | toYaml | nindent 14 }}
          config:
            modules:
              http_2xx_proxified:
                prober: http
                timeout: 5s
                http:
                  valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
                  follow_redirects: true
                  preferred_ip_protocol: "ip4"
                  proxy_url: {{ .Values.cluster.httpProxy }}
                  fail_if_ssl: false
                  fail_if_not_ssl: false
                  tls_config:
                    insecure_skip_verify: true

        prometheus:
          enabled: {{ .Values.apps.prometheus.enabled }}
          rules:
            enabled: {{ .Values.apps.prometheus.enabled }}
            labels:
              prometheus: {{ include "prometheus.label" . | quote }}  
        grafanaDashboard:
          enabled: {{ .Values.apps.grafana.enabled }}
        internalServices:
          hsm:
            enabled: true
            externalUrl: {{ .Values.apps.blackboxExporter.hsmExternalUrl }}
          hsmPreprod:
            enabled: {{ .Values.apps.blackboxExporter.hsmPreprodEnable }}
            externalUrl: {{ .Values.apps.blackboxExporter.hsmPreprodExternalUrl }}
          proxy:
            enabled: true
            externalUrl: {{ .Values.apps.blackboxExporter.proxyExternalUrl }}
          vault:
            enabled: true
            externalUrl: {{ .Values.apps.blackboxExporter.vaultExternalUrl }}
          smtp:
            enabled: true
            externalUrl: {{ .Values.apps.blackboxExporter.smtpExternalUrl }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ include "blackboxExporter.namespace" . | quote }}

  {{- include "infra.syncPolicy" (list . "blackboxExporter" ) | nindent 2 }}

{{- end }}