{{- if .Values.apps.dynaKubeOperator.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: dynakube-operator
spec:
  project: {{ include "dynaKubeOperator.appproject" . }}
  source:
    repoURL: {{ .Values.cluster.ociRepoUrl | quote }}
    targetRevision: {{ .Values.apps.dynaKubeOperator.targetRevision | quote }}
    chart: dynakube-operator
    helm:
      values: |
        dynatraceOperator:
          {{- if eq .Values.apps.dynaKubeOperator.targetRevision "0.1.25" }}
          imageRef:
            repository: {{ .Values.apps.dynaKubeOperator.dynaKubeOperatorImageRepo }}
            tag: {{ .Values.apps.dynaKubeOperator.dynaKubeOperatorImageTag }}
          {{- else }}
          image: {{ .Values.apps.dynaKubeOperator.dynaKubeOperatorImageRepo }}:{{ .Values.apps.dynaKubeOperator.dynaKubeOperatorImageTag }}
          {{- end }}
          customPullSecret:  {{ toYaml (index .Values.cluster.imagePullSecrets 0).name }}
          csidriver:
            enabled: {{ .Values.apps.dynaKubeOperator.csiDriver.enabled }}
        dynakube:
          networkZone: {{ .Values.apps.dynaKubeOperator.networkZone | quote }}
          classicFullStack:
            enabled: {{ .Values.apps.dynaKubeOperator.classicFullStack.enabled }}
            apiUrl: {{ .Values.apps.dynaKubeOperator.classicFullStack.apiUrl | quote }}
            proxySecret: "{{ .Values.cluster.proxyEnvSecret }}"
            oneAgent:
              env:
              - name: ONEAGENT_ENABLE_VOLUME_STORAGE
                value: "true"
              args:
                {{- .Values.apps.dynaKubeOperator.classicFullStack.oneAgent.args | toYaml | nindent 14 }}
            activeGate:
              replicas: {{ .Values.apps.dynaKubeOperator.classicFullStack.activeGate.replicas }}
              env:
              # - name: HTTP_PROXY
              #   value: "{{ .Values.cluster.httpProxy }}"
              # - name: HTTPS_PROXY
              #   value: "{{ .Values.cluster.httpProxy }}"
              - name: NO_PROXY
                value: "{{ .Values.cluster.noProxy }}"
              group: {{ .Values.apps.dynaKubeOperator.classicFullStack.activeGate.group }}
        prometheus:
          enabled: {{ .Values.apps.prometheus.enabled }}
          rules:
            labels:
              prometheus: {{ include "prometheus.label" . | quote }}
        vault:
          enabled: false
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
    - /spec/preserveUnknownFields
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ include "dynaKubeOperator.namespace" . | quote }}

  {{- include "infra.syncPolicy" (list . "dynaKubeOperator" ) | nindent 2 }}

{{- end }}
