{{- if .Values.apps.externalSecretsOperator.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: external-secrets-operator
spec:
  project: {{ include "external-secrets-operator.appproject" . }}
  source:
    repoURL: {{ .Values.cluster.ociRepoUrl | quote }}
    targetRevision: {{ .Values.apps.externalSecretsOperator.targetRevision | quote }}
    chart: external-secrets-operator
    helm:
      values: |
        extsecoper:
          serviceAccount:
            create: {{ .Values.apps.externalSecretsOperator.serviceAccount.create }}
            name: {{ .Values.apps.externalSecretsOperator.serviceAccount.name }}
            annotations: {{ .Values.apps.externalSecretsOperator.serviceAccount.annotations | toYaml | nindent 14 }}
        {{- if .Values.cluster.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml .Values.cluster.imagePullSecrets | nindent 10 }}
        {{- end }}
          image:
            repository: {{ .Values.apps.externalSecretsOperator.externalSecretsImageRepo | quote }}
            tag: {{ .Values.apps.externalSecretsOperator.externalSecretsImageTag | quote }}
            pullPolicy: {{ .Values.apps.externalSecretsOperator.imagePullPolicy | quote }}
          resources:
            {{- .Values.apps.externalSecretsOperator.resources | toYaml | nindent 12 }}
          extraEnv:
            {{- .Values.apps.externalSecretsOperator.env | toYaml | nindent 12 }}
          webhook:
          {{- if .Values.cluster.imagePullSecrets }}
            imagePullSecrets:
            {{- toYaml .Values.cluster.imagePullSecrets | nindent 12 }}
          {{- end }}
            image:
              repository: {{ .Values.apps.externalSecretsOperator.externalSecretsImageRepo | quote }}
              tag: {{ .Values.apps.externalSecretsOperator.externalSecretsImageTag | quote }}
          certController:
          {{- if .Values.cluster.imagePullSecrets }}
            imagePullSecrets:
            {{- toYaml .Values.cluster.imagePullSecrets | nindent 12 }}
          {{- end }}
            image:
              repository: {{ .Values.apps.externalSecretsOperator.externalSecretsImageRepo | quote }}
              tag: {{ .Values.apps.externalSecretsOperator.externalSecretsImageTag | quote }}
          prometheus:
            enabled: {{ .Values.apps.prometheus.enabled }}
            serviceMonitor:
              enabled: {{ .Values.apps.prometheus.enabled }}
              interval: "30s"
              port: "8080"
              labels:
                prometheus: {{ include "prometheus.label" . | quote }}
            rules:
              platform:
                enabled: {{ .Values.apps.prometheus.enabled }}
              service:
                enabled: {{ .Values.apps.prometheus.enabled }}
              labels:
                prometheus: {{ include "prometheus.label" . | quote }}
        grafanaDashboards:
          enabled: {{ .Values.apps.prometheus.enabled }}

  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
      - /spec/preserveUnknownFields

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ include "external-secret-operator.namespace" . | quote }}
  
  {{- include "infra.syncPolicy" (list . "externalSecretsOperator" ) | nindent 2 }}

{{- end }}
