{{- if .Values.apps.gatekeeper.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: gatekeeper
spec:
  project: {{ include "gatekeeper.appproject" . }}
  source:
    repoURL: {{ .Values.cluster.ociRepoUrl | quote }}
    targetRevision: {{ .Values.apps.gatekeeper.targetRevision | quote }}
    chart: gatekeeper-operator
    helm:
      values: |
        gatekeeper:
          image:
            repository: {{ .Values.apps.gatekeeper.gatekeeperImageRepo | quote }}
            crdRepository: {{ .Values.apps.gatekeeper.gatekeeperCrdImageRepo | quote }}
            release: {{ .Values.apps.gatekeeper.gatekeeperRelease | quote }}
            {{- if .Values.cluster.imagePullSecrets }}
            pullSecrets:
            {{- toYaml .Values.cluster.imagePullSecrets | nindent 12 }}
            {{- end }}
          postInstall:
            labelNamespace:
              extraNamespaces:
              - kube-system
              image:
                repository: {{ .Values.apps.gatekeeper.postInstallImageRepo | quote }}
                tag: {{ .Values.apps.gatekeeper.gatekeeperImageTag | quote }}
               {{- if .Values.cluster.imagePullSecrets }}
                pullSecrets:
                {{- toYaml .Values.cluster.imagePullSecrets | nindent 16 }}
               {{- end }}
            {{- if and .Values.apps.gatekeeper.probeWebhookImageRepo .Values.apps.gatekeeper.probeWebhookImageTag }}
            probeWebhook:
              image:
                repository: {{ .Values.apps.gatekeeper.probeWebhookImageRepo | quote }}
                tag: {{ .Values.apps.gatekeeper.probeWebhookImageTag | quote }}
               {{- if .Values.cluster.imagePullSecrets }}
                pullSecrets:
                {{- toYaml .Values.cluster.imagePullSecrets | nindent 16 }}
               {{- end }}
            {{- end }}              
          auditFromCache: {{ .Values.apps.gatekeeper.auditFromCache }}
          audit:
            resources:
              {{- .Values.apps.gatekeeper.audit.resources | toYaml | nindent 14 }}
          controllerManager:
            exemptNamespacePrefixes: ["kube-"]
            port: {{ .Values.apps.gatekeeper.controllerManager.port }}
            resources:
              {{- .Values.apps.gatekeeper.controllerManager.resources | toYaml | nindent 14 }}
        prometheus:
          enabled: {{ .Values.apps.gatekeeper.prometheus.enabled }}
          serviceMonitor:
            enabled: {{ .Values.apps.gatekeeper.prometheus.serviceMonitor.enabled }}
          rules:
            labels:
              prometheus: prometheus-operator-prometheus
        grafanaDashboard:
          enabled: {{ .Values.apps.gatekeeper.grafanaDashboard.enabled }}
        config:
          syncOnly:
          - group: ""
            version: "v1"
            kind: "Namespace"
          - group: "networking.k8s.io"
            version: "v1"
            kind: "Ingress"
          - group: "apps"
            version: "v1"
            kind: "Deployment"
          - group: ""
            version: "v1"
            kind: "Pod"
          match:
          - excludedNamespaces: ["kube-*", {{ include "gatekeeper.namespace" . | quote }}]
            processes: ["*"]
          - excludedNamespaces: ["audit-excluded-ns"]
            processes: ["audit"]
          - excludedNamespaces: ["audit-webhook-sync-excluded-ns"]
            processes: ["audit", "webhook", "sync"]
          - excludedNamespaces: ["mutation-excluded-ns"]
            processes: ["mutation-webhook"]
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
      - /spec/preserveUnknownFields

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ include "gatekeeper.namespace" . | quote }}

  {{- include "infra.syncPolicy" (list . "gatekeeper" ) | nindent 2 }}

{{- end }}
