{{- if .Values.apps.kubed.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubed
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: {{ include "kubed.appproject" . }}
  source:
    repoURL: {{ .Values.cluster.ociRepoUrl | quote }}
    targetRevision: {{ .Values.apps.kubed.targetRevision | quote }}
    chart: kubed
    helm:
      values: |
        kubed:
        {{- if .Values.cluster.imagePullSecrets }}
          imagePullSecrets:
          {{- toYaml .Values.cluster.imagePullSecrets | nindent 10 }}
        {{- end }}
        {{- if .Values.apps.kubed.dynatraceMonitoring.enabled }}
          podAnnotations:
              metrics.dynatrace.com/path: /metrics
              metrics.dynatrace.com/port: "8443"
              metrics.dynatrace.com/scrape: "true"
              metrics.dynatrace.com/secure: "true"
        {{- end }}
          operator:
            registry: {{ .Values.apps.kubed.kubedRegistryName | quote }}
            repository: {{ .Values.apps.kubed.kubedRepositoryName | quote }}
            tag: {{ .Values.apps.kubed.kubedImageTag | quote }}
          enableAnalytics: {{ .Values.apps.kubed.enableAnalytics }}
          criticalAddon: {{ .Values.apps.kubed.enableAddon }}
          config:
            clusterName: {{ .Values.apps.kubed.clusterName }}
          apiserver:
            healthcheck:
              enabled: {{ .Values.apps.kubed.enableHealthCheck }}
          prometheus:
            enabled: {{ .Values.apps.kubed.prometheus.enabled }}
            serviceMonitor:
              enabled: {{ .Values.apps.kubed.prometheus.servicemonitor.enabled }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ include "kubed.namespace" . | quote }}

  {{- include "infra.syncPolicy" (list . "kubed" ) | nindent 2 }}

  ignoreDifferences:
  - kind: Secret
    jsonPointers:
    - /data/tls.crt
    - /data/tls.key
  - group: "apps/v1"
    kind: Deployment
    jsonPointers:
    - /spec/template/metadata/annotations

{{- end }}
