{{- if .Values.apps.prometheusOperator.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: prometheus-operator
spec:
  project: {{ include "prometheus-operator.appproject" . }}
  source:
    repoURL: {{ .Values.cluster.ociRepoUrl | quote }}
    targetRevision: {{ .Values.apps.prometheusOperator.targetRevision | quote }}
    chart: prometheus-operator
    helm:
      values: |
        prometheusOperator:
          global:
          {{- if .Values.cluster.imagePullSecrets }}
            imagePullSecrets:
            {{- toYaml .Values.cluster.imagePullSecrets | nindent 12 }}
          {{- end }}
          prometheusOperator:
            image:
              repository: {{ .Values.apps.prometheusOperator.prometheusOperatorImageRepo | quote }}
              tag: {{ .Values.apps.prometheusOperator.prometheusOperatorImageTag | quote }}
            prometheusConfigReloader:
              image:
                repository: {{ .Values.apps.prometheusOperator.prometheusConfigReloaderImageRepo | quote }}
                tag: {{ .Values.apps.prometheusOperator.prometheusConfigReloaderImageTag | quote }}
            admissionWebhooks:
                patch:
                  image:
                    repository: {{ .Values.apps.prometheusOperator.kubeWebhookCertgenImageRepo | quote }}
                    tag: {{ .Values.apps.prometheusOperator.kubeWebhookCertgenImageTag | quote }}
            {{- if .Values.apps.prometheusOperator.priorityClassName }}
            priorityClassName: "{{ .Values.apps.prometheusOperator.priorityClassName }}"
            {{- end }}
          prometheus-node-exporter:
            customLabels:
              prometheus: {{ include "prometheus.label" . }}
            serviceAccount:
            {{- if .Values.cluster.imagePullSecrets }}
              imagePullSecrets:
            {{- toYaml .Values.cluster.imagePullSecrets | nindent 14 }}
            {{- end }}
            image:
              repository: {{ .Values.apps.prometheusOperator.nodeExporterImageRepo | quote }}
              tag: {{ .Values.apps.prometheusOperator.nodeExporterImageTag | quote }}
            {{- if .Values.apps.prometheusOperator.priorityClassName }}
            priorityClassName: {{ .Values.apps.prometheusOperator.priorityClassName }}
            {{- end }}
          kube-state-metrics: 
            customLabels:
              prometheus: {{ include "prometheus.label" . }}
            image:
              repository: {{ .Values.apps.prometheusOperator.kubeStateMetricsImageRepo | quote }}
              tag: {{ .Values.apps.prometheusOperator.kubeStateMetricsImageTag | quote }}
            {{- if .Values.apps.prometheusOperator.priorityClassName }}
            priorityClassName: {{ .Values.apps.prometheusOperator.priorityClassName }}
            {{- end }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ include "prometheus-operator.namespace" . | quote }}

  {{- include "infra.syncPolicy" (list . "prometheusOperator" ) | nindent 2 }}

  ignoreDifferences:
      - group: "admissionregistration.k8s.io"
        kind: "ValidatingWebhookConfiguration"
        jsonPointers:
          - /webhooks/0/failurePolicy
      - group: "admissionregistration.k8s.io"
        kind: "MutatingWebhookConfiguration"
        jsonPointers:
          - /webhooks/0/failurePolicy
{{- end }}
