{{- if .Values.apps.stackdriverExporter.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: stackdriver-exporter
spec:
  project: {{ include "stackdriverExporter.appproject" . }}
  source:
    repoURL: {{ .Values.cluster.ociRepoUrl | quote }}
    targetRevision: {{ .Values.apps.stackdriverExporter.targetRevision | quote }}
    chart: prometheus-stackdriver-exporter
    helm:
      values: |
        stackdriver-exporter:
          image:
            repository: {{ .Values.apps.stackdriverExporter.stackdriverExporterImageRepo }}
            tag: {{ .Values.apps.stackdriverExporter.stackdriverExporterImageTag }}
            {{-  if .Values.cluster.imagePullSecrets }}
            pullSecrets:
              - {{  toYaml (index .Values.cluster.imagePullSecrets 0).name }}
            {{- end }}
          stackdriver:
            projectId: {{ .Values.cluster.gcpProjectId }}
            metrics:
              typePrefixes: {{ .Values.apps.stackdriverExporter.stackdriverExporterTypePrefixes }}
          serviceMonitor:
            enabled:  {{ .Values.apps.prometheus.enabled }}
            namespace: {{ include "prometheus.namespace" . | quote }}
            additionalLabels:
              prometheus: {{ include "prometheus.label" . | quote }} 
        prometheus:
          rules:
            enabled: {{ .Values.apps.prometheus.enabled }}
            labels:
              prometheus: {{ include "prometheus.label" . | quote }}  
        grafanaDashboard:
          enabled: {{ .Values.apps.grafana.enabled }}

  destination:
    server: https://kubernetes.default.svc
    namespace: {{ include "stackdriverExporter.namespace" . | quote }}

  {{- include "infra.syncPolicy" (list . "stackdriverExporter" ) | nindent 2 }}

{{- end }}